server {
    listen 80;
    server_name _;

    # SPA: todo cae a index.html (Caddy/Traefik en el gateway maneja /api/*)
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}
